

DROP TABLE ITENS_COMANDA;
DROP TABLE COMANDA;
DROP TABLE PRODUTOS;
DROP TABLE CATEGORIAS;


CREATE TABLE CATEGORIAS
(
	COD_CATEGORIA		INT IDENTITY(1,1) NOT NULL,
	CATEGORIA			VARCHAR(50) NOT NULL,	
	CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY (COD_CATEGORIA)
);

CREATE TABLE PRODUTOS
(
	COD_PRODUTO		INT IDENTITY(100,1) NOT NULL,
	COD_CATEGORIA	INT NOT NULL,
	DESCRICAO		VARCHAR (50) NOT NULL,
	PRECO			DECIMAL (5,2) NOT NULL,
	OBSERVACOES		VARCHAR (50),
	CONSTRAINT [PK_PRODUTOS] PRIMARY KEY (COD_PRODUTO),
	CONSTRAINT FK_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS(COD_CATEGORIA)
);


CREATE TABLE COMANDA
(
	COD_COMANDA		INT IDENTITY(1000,1) NOT NULL,
	NOME_CLIENTE	VARCHAR(50) NOT NULL,
	DATA_INICIO		DATE NOT NULL,
	DATA_FIM		DATE NOT NULL,
	STATUS			VARCHAR(12) NOT NULL,
	VALOR_TOTAL		DECIMAL (5,2),
	CONSTRAINT [PK_COMANDA] PRIMARY KEY (COD_COMANDA) 
);

CREATE TABLE ITENS_COMANDA
(
	COD_ITEM				INT IDENTITY(1,1) NOT NULL,
	COD_PRODUTO		INT NOT NULL,
	COD_COMANDA		INT NOT NULL,
	OBSERVACOES		VARCHAR (50),
	CONSTRAINT PK_ITENS_COMANDA PRIMARY KEY (COD_ITEM),
	CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS(COD_PRODUTO),
	CONSTRAINT FK_COMANDA FOREIGN KEY (COD_COMANDA) REFERENCES COMANDA(COD_COMANDA)
	
);
