

INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('BEBIDAS'); --1
INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('CERVEJA'); --2
INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('OUTROS'); --3
INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('CALDOS'); --4

INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('1','AGUA','5.00'); --1
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('1','COCA-COLA','4.00'); --2
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('2','SKOL','2.50'); --3
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('2','BRAHMA','2.00'); --4
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('3','CAMPARI(DOSE)','8.00'); --5
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('3','VODKA(DOSE)','12.00'); --6
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('4','VERDE','11.00'); --7
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('4','MOCOTÓ','9.00'); --8
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('4','GALINHA','6.00'); --9

INSERT INTO COMANDA(NOME_CLIENTE, DATA_ATUAL, STATUS) VALUES('CESAR','21/06/2016','ABERTO'); --1
INSERT INTO COMANDA(NOME_CLIENTE, DATA_ATUAL, STATUS) VALUES('LILIAN','22/06/2016','ABERTO'); --2
INSERT INTO COMANDA(NOME_CLIENTE, DATA_ATUAL, STATUS) VALUES('JOÃO','23/06/2016','ABERTO'); --3

INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('1','1');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('3','1');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('9','1');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('4','2');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('3','2');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('7','2');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('6','3');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('3','3');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('8','3');