
DROP TABLE PAGAMENTOS;
DROP TABLE ITENS_COMANDA;
DROP TABLE COMANDA;
DROP TABLE PRODUTOS;
DROP TABLE CATEGORIAS;

CREATE TABLE CATEGORIAS
(
	COD_CATEGORIA		INT IDENTITY(1,1) NOT NULL,
	CATEGORIA			VARCHAR(50) NOT NULL,	
	CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY (COD_CATEGORIA)
);

CREATE TABLE PRODUTOS
(
	COD_PRODUTO		INT IDENTITY(100,1) NOT NULL,
	COD_CATEGORIA	INT NOT NULL,
	DESCRICAO		VARCHAR (50) NOT NULL,
	PRECO			DECIMAL (5,2) NOT NULL,
	OBSERVACOES		VARCHAR (50),
	CONSTRAINT [PK_PRODUTOS] PRIMARY KEY (COD_PRODUTO),
	CONSTRAINT FK_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS(COD_CATEGORIA)
);


CREATE TABLE COMANDA
(
	COD_COMANDA		INT IDENTITY(1000,1) NOT NULL,
	NOME_CLIENTE	VARCHAR(50) NOT NULL,
	DATA_INICIO		DATE NOT NULL,
	DATA_FINAL		DATE,
	STATUS			VARCHAR(12) NOT NULL,
	VALOR_TOTAL		DECIMAL (5,2),
	CONSTRAINT [PK_COMANDA] PRIMARY KEY (COD_COMANDA) 
);

CREATE TABLE ITENS_COMANDA
(
	COD_ITEM		INT IDENTITY(1,1) NOT NULL,
	COD_PRODUTO		INT NOT NULL,
	COD_COMANDA		INT NOT NULL,
	OBSERVACOES		VARCHAR (50),
	CONSTRAINT PK_ITENS_COMANDA PRIMARY KEY (COD_ITEM),
	CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS(COD_PRODUTO),
	CONSTRAINT FK_COMANDA FOREIGN KEY (COD_COMANDA) REFERENCES COMANDA(COD_COMANDA)
	
);

CREATE TABLE PAGAMENTOS
(
	COD_PAGAMENTO	INT IDENTITY(1,1) NOT NULL,
	COD_COMANDA		INT NOT NULL,
	PAG_OBSERVACOES	VARCHAR (100),
	VALOR_PAGO		DECIMAL (5,2),
	CONSTRAINT PK_PAGAMENTOS PRIMARY KEY (COD_PAGAMENTO),
	CONSTRAINT FK_COMANDA2 FOREIGN KEY (COD_COMANDA) REFERENCES COMANDA(COD_COMANDA)
);
--------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('CERVEJA'); --1
INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('BEBIDAS'); --2
INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('LANCHES/CALDOS'); --3
INSERT INTO CATEGORIAS(CATEGORIA)VALUES ('OUTROS'); --4

INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','SKOL','2.50','239ML'); --100
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','BRAHMA','4.00','350ML'); --101
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','HEINIKEN','9.00','600ML'); --102
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','FAXE PREMIUM','20.00','1000ML'); --103
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','EISENBAHN PILSEN','9.00','355ML'); --104
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','GANGSTER ALE','18.00','355ML'); --105
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','BARCO LAGER','28.00','1000ML'); --106
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','COLORADO BERTHÔ','18.00','600ML'); --107
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','COLORADO IPA','16.00','600ML'); --121
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('1','BOHEMIA','08.00','600ML'); --122

INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('2','AGUA','5.00','500ML'); --108
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('2','COCA-COLA','4.00','350ML'); --109
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('2','SUCO DELL VALE','4.00','350ML'); --110
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('2','FANTA','4.00','350ML'); --111
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('2','AGUA DE COCO','5.00','300ML'); --112

INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('3','VERDE','11.00'); --113
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('3','MOCOTÓ','9.00'); --114
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('3','GALINHA','6.00'); --115
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO) VALUES('3','PIRANHA','6.00'); --116

INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('4','CAMPARI','8.00','DOSE'); --117
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('4','VODKA','12.00','DOSE'); --118
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('4','RED BULL','8.00','250ML'); --119
INSERT INTO PRODUTOS(COD_CATEGORIA, DESCRICAO, PRECO, OBSERVACOES) VALUES('4','WHISKY RED LABEL','15.00','DOSE'); --120

INSERT INTO COMANDA(NOME_CLIENTE, DATA_INICIO, STATUS) VALUES('CESAR','21/06/2016','ABERTO'); --1000
INSERT INTO COMANDA(NOME_CLIENTE, DATA_INICIO, STATUS) VALUES('LILIAN','22/06/2016','ABERTO'); --1002
INSERT INTO COMANDA(NOME_CLIENTE, DATA_INICIO, STATUS) VALUES('JOÃO','23/06/2016','ABERTO'); --1003

INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('100','1000');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('102','1000');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('108','1000');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('103','1001');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('102','1001');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('106','1001');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('105','1002');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('104','1002');
INSERT INTO ITENS_COMANDA(COD_PRODUTO, COD_COMANDA)VALUES('107','1002');

INSERT INTO PAGAMENTOS(COD_COMANDA, PAG_OBSERVACOES, VALOR_PAGO) VALUES('1000','ALGUEM PAGOU','5.00');
INSERT INTO PAGAMENTOS(COD_COMANDA, PAG_OBSERVACOES, VALOR_PAGO) VALUES('1001','ALGUEM PAGOU','8.00');
INSERT INTO PAGAMENTOS(COD_COMANDA, PAG_OBSERVACOES, VALOR_PAGO) VALUES('1002','ALGUEM PAGOU','7.40');
--------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM CATEGORIAS;
SELECT * FROM PRODUTOS;
SELECT * FROM COMANDA;
SELECT * FROM ITENS_COMANDA;
SELECT * FROM PAGAMENTOS;

SELECT C.COD_COMANDA AS COMANDA, C.NOME_CLIENTE AS CLIENTE, P.DESCRICAO AS PRODUTOS, P.OBSERVACOES, CA.CATEGORIA, P.PRECO
FROM ITENS_COMANDA I
INNER JOIN COMANDA C ON C.COD_COMANDA = I.COD_COMANDA
INNER JOIN PRODUTOS P ON P.COD_PRODUTO = I.COD_PRODUTO
INNER JOIN CATEGORIAS CA ON CA.COD_CATEGORIA = P.COD_CATEGORIA
WHERE I.COD_COMANDA='1000'

SELECT COD_CATEGORIA, COUNT(*)FROM PRODUTOS GROUP BY COD_CATEGORIA;

-- nome e quantidade de produtos separados por categorias
SELECT C.CATEGORIA,
	(SELECT COUNT(*) FROM PRODUTOS
	WHERE COD_CATEGORIA = C.COD_CATEGORIA)AS 'QUANTIDADE'
	FROM CATEGORIAS C;
	
SELECT I.COD_PRODUTO, P.PRECO
FROM ITENS_COMANDA I
INNER JOIN PRODUTOS P ON P.COD_PRODUTO = I.COD_PRODUTO
WHERE I.COD_COMANDA = '1000'

SELECT 
	P.DESCRICAO,
(SELECT  
	COUNT(*) AS CONT FROM ITENS_COMANDA IC
WHERE 
	P.COD_PRODUTO = IC.COD_PRODUTO) AS 'QUANTIDADE' 
FROM 
	PRODUTOS P;
	
	
SELECT 
	P.DESCRICAO,P.PRECO, COUNT(P.PRECO) AS CONT 
FROM 
	ITENS_COMANDA IC, PRODUTOS P
WHERE 
	P.COD_PRODUTO = IC.COD_PRODUTO 
		AND
	IC.COD_COMANDA = '1000'
GROUP BY 
	P.DESCRICAO, P.PRECO 
